Add 3 sections
SvetlomirBalevski/workshop pull request #5
Opened 2023-03-14 00:15 UTC by asankov

- build
- Docker build
- Docker scan

There are some TODOs that will be resolved before merging.

I have not added any numbers to the sections, or links, because the order will probably change when we merge this with @SvetlomirBalevski 's work.

2023-03-14 07:00 UTC, SvetlomirBalevski requested changes

2023-03-14 07:00 UTC, SvetlomirBalevski commented on 0x-docker-build/README.md
> +
Docker pipeline plugin should be installed first (https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/Fix-Jenkins-Invalid-agent-type-Docker-specified-any-label-none-error).

We can leave it without explanation if we decide to reduce hand holding.

2023-03-15 19:46 UTC, asankov commented on 0x-docker-build/README.md
> +
if we merge https://github.com/SvetlomirBalevski/secure-pipeline-example/pull/1 the docker pipeline plugin will be installed alongside Jenkins

2023-03-16 20:03 UTC, SvetlomirBalevski approved these changes

2023-03-16 20:05 UTC, merged